.prettierrc
.prettierrc.yml
.vscode/settings.json

- removed prettier.yml file
- added new .prettierrc file 
---

Fix - updated prettier settings. Enabled autosave for workspace setting

---

client/Game.js
client/app.js
client/clean.css
client/components/auth-form.js
client/components/index.js
client/components/navbar.js
client/components/user-home.js
client/components/user-home.spec.js
client/history.js
client/index.js
client/routes.js
client/store/index.js
client/store/user.js
client/store/user.spec.js
package-lock.json
package.json
public/index.css
public/index.html
server/api/games.js
server/api/index.js
server/api/utils.js
server/db/config.js
webpack.config.js

Initial view

---

server/db/config.js

Fix - updated firebase credentials

---

server/db/config.js

Fix - updated heroku credentials

---

client/clean.css
package-lock.json
package.json
webpack.config.js

Fix - updated to get clean.css working

---

client/Game.js
server/api/games.js
server/api/index.js
server/api/wiki.js

- fixed handle click
- optimized routes
---

Feature click logic

---

server/api/games.js
server/api/wiki.js

fixed getting article title

---

client/Game.js
server/api/games.js

Generate Game resets user info

---

client/Game.js
client/components/GlobalGameInfo.js

Bugfix titles

---

server/db/config.js

Firebase package updated for travis

---

client/Game.js
client/components/leaderboard/GameStats.js
client/components/leaderboard/LeaderboardContainer.js
client/components/leaderboard/UserStats.js
server/api/globalGame.js
server/api/wiki.js

Bugfix playgame

---

client/components/login/UserName.js

Fix: Username - updated username to save correctly under Users

---

client/components/leaderboard/UserStats.js
server/api/wiki.js

also added start/end time to leaderboard for eventual display/timer testing

fix: improved link handling to accept accents and commas

---

client/Game.js
client/Navbar.js
client/components/Finished.js
client/components/InGame.js
client/components/Pregame.js
client/components/login/LoginComplete.spec.js
server/api/globalGame.js
server/api/utils.js
server/db/config.js

Deployment

---

client/Game.js
server/db/config.js

hotfixes fore code review

---

client/Buttons.js
client/Game.js
client/Navbar.js
server/api/globalGame.js

Game buttons

---

client/Game.js

removed timer logs

---

client/Game.js
client/components/InGame.js
client/components/leaderboard/GameStats.js
client/components/leaderboard/LeaderboardContainer.js
client/components/leaderboard/UserStats.js
client/components/leaderboard/leaderboard.css
server/api/globalGame.js

Usernames - added username to the leaderboard

---

package-lock.json
server/api/globalGame.js

Fix - updating the time

---

client/Game.js

test: changed process.env.HOST to herokuapp

---

client/Game.js

test: hardcoded HOST

---

server/api/globalGame.js

fix: game time to actual times

---

public/style.css

hotfix for font size

---

client/Game.js
server/api/users.js

fixed user api game history route

---

client/Game.js

Updated routes to heroku

---

client/Game.js
client/components/stats/Stats.js
public/index.html

changes for switch to wikilinks.app

---

server/api/globalGame.js

Hardcoded titles

---

server/api/globalGame.js

Fixed underscores in titles
